### ISSUE TITLE
Files don't appear in stats.compilation.assets on webpack --watch builds

### ISSUE THREAD

**Issue by kevlened** [kevlened/copy-webpack-plugin#14]
Files appear in stat.compilation.assets on the first build, but subsequent builds don't include assets added by the copy-webpack-plugin, even though updated files are actually copied.

**Comment by gajus** [comment]
Note that if target resources is modified, it will appear in `stat.compilation.assets`. Therefore, this is not necessarily an issue.

**Comment by gajus** [comment]
Here is the reason it is being excluded, https://github.com/kevlened/copy-webpack-plugin/blob/d47a06ede412a4982991014076c6e88b2293497b/index.js#L148-L157:

```js
if (stat.mtime.getTime() > lastGlobalUpdate) {
  compilation.assets[relFileDest] = {
    size: function() {
      return stat.size;
    },
    source: function() {
      return fs.readFileSync(absFileSrc);
    }
  };
}
```

I'd like to remove this and delegate the responsibility to https://github.com/gajus/write-file-webpack-plugin. Otherwise (as evident), it is confusing that the asset suddenly no longer appears in the `stat.compilation.assets` collection.

**Comment by gajus** [comment]
https://github.com/kevlened/copy-webpack-plugin/pull/20
