### ISSUE TITLE
An exception on /**/* path with nested folders

### ISSUE THREAD

**Issue by stq** [kevlened/copy-webpack-plugin#24]
When using path like assets/ * * / * to copy a number of files in nested folders, an exception is occured:
**A global exception occured: { [Error: EINVAL: invalid argument, read] errno: -4071, code: 'EINVAL', syscall: 'read' }**
A number of messages with exception match total number of nested folders, so seems like folders are causing it.
But files and folders are still copied successfully, if to handle global exceptions manually.

Replacing path with assets/ * * / * . * fixes issue. But probably this workaround would't work for files without extension.

**Comment by kirbysayshi** [comment]
+1 this just bit me too.

**Comment by MatthewKosloski** [comment]
Same!

My file structure:
```
src
    assets
        fonts
	img
webpack.config.js
```

My plugin:

```
{from: 'src/assets/**/*', to: 'assets'}
```

With this Webpack output path:

```
path: path.join(__dirname, 'public')
```

Results in:

```
public
    assets
        src
	    assets
	        fonts
```

**Comment by joepagan** [comment]
Not sure why this has closed, this just happened to me too on webpack4.

When using a glob pattern in the `from` path: `path/**/*` it copys the dir structure over to the` to` path.

It appears that just stating the directory as @MatthewKosloski has done, it will glob the files within anyway.

**Comment by evilebottnawi** [comment]
@joepagan Can you create minimum reproducible test repo?

**Comment by joepagan** [comment]
@evilebottnawi Of course!

This maybe because it's on `webpack-dev-server`? The others didn't say. [I have seen the large issue where some users want the files to exist when running dev server](https://github.com/webpack-contrib/copy-webpack-plugin/issues/29), though I am happy for these to be in the memory.

Here is the repo for you:
https://github.com/joepagan/webpack-copywebpackplugin-glob-issue

just clone, `yarn; yarn start`

Visit:
http://localhost:8080/webpack-dev-server

![image](https://user-images.githubusercontent.com/2337910/36872755-38fe31ce-1d9e-11e8-8b5f-97f8b6202137.png)


Now comment out the glob rules in `webpack.common.js` lines 94-97, and, uncomment 98-101

The paths are then as expected:
![image](https://user-images.githubusercontent.com/2337910/36872532-788727fc-1d9d-11e8-87f1-e6a297fafcf8.png)
